# Generated by Django 6.0.4 on 2026-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('numero_imovel', models.CharField(max_length=50, unique=True, verbose_name='Nº do Imóvel')),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de desconto', max_digits=5, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=32, null=True)),
                ('last_seen', models.DateField(auto_now=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Leilão',
                'verbose_name_plural': 'Leilões',
                'ordering': ['-last_seen', 'preco'],
            },
        ),
    ]
