# Generated by Django 6.0.4 on 2026-04-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bairro',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='cidade',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual ou valor de desconto', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='last_seen',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='modalidade',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='preco',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='uf',
            field=models.CharField(db_index=True, max_length=2, verbose_name='UF'),
        ),
        # migrations.AlterModelTable(
        #     name='auction',
        #     table='current_imoveis',
        # ),
        # migrations.CreateModel(
        #     name='AuctionEvent',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('dt', models.DateField(verbose_name='Data do Evento')),
        #         ('uf', models.CharField(max_length=2)),
        #         ('tipo_evento', models.CharField(choices=[('ENTER', 'Entrada'), ('EXIT', 'Saída'), ('UPDATE', 'Atualização')], max_length=10)),
        #         ('numero_imovel', models.CharField(max_length=50)),
        #         ('changed_fields', models.TextField(blank=True, null=True)),
        #         ('before_json', models.JSONField(blank=True, null=True)),
        #         ('after_json', models.JSONField(blank=True, null=True)),
        #         ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='auctions.auction')),
        #     ],
        #     options={
        #         'verbose_name': 'Evento de Leilão',
        #         'verbose_name_plural': 'Eventos de Leilão',
        #         'db_table': 'changes',
        #         'ordering': ['-dt'],
        #     },
        # ),
    ]
