# Generated by Django 6.0.4 on 2026-08-20 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_bairro_alter_auction_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=False, verbose_name='Ativa')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim (validade)')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('ENTER', 'Adição'), ('EXIT', 'Remoção'), ('UPDATE', 'Alteração')], max_length=10)),
                ('numero_imovel', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('dt', models.DateField()),
                ('canais', models.JSONField(blank=True, default=list)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação Enviada',
                'verbose_name_plural': 'Notificações Enviadas',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF')),
                ('cidades', models.JSONField(blank=True, default=list, verbose_name='Cidades')),
                ('bairros', models.JSONField(blank=True, default=list, verbose_name='Bairros')),
                ('modalidades', models.JSONField(blank=True, default=list, verbose_name='Modalidades')),
                ('canal_email', models.BooleanField(default=True, verbose_name='Notificar por e-mail')),
                ('canal_whatsapp', models.BooleanField(default=False, verbose_name='Notificar por WhatsApp')),
                ('contato_whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp (DDI+DDD+número)')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Preferência de Alerta',
                'verbose_name_plural': 'Preferências de Alertas',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='dados_enriquecidos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='dados_enriquecidos_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='tipo_imovel',
            field=models.CharField(blank=True, choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('terreno', 'Terreno'), ('outro', 'Outro')], db_index=True, max_length=20, null=True, verbose_name='Tipo de Imóvel'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['uf', 'cidade'], name='idx_uf_cidade'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['uf', 'cidade', 'bairro'], name='idx_uf_cidade_bairro'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['uf', 'modalidade'], name='idx_uf_modalidade'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['cidade', 'modalidade'], name='idx_cidade_modalidade'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['preco'], name='idx_preco'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['valor_avaliacao'], name='idx_valor_avaliacao'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['tipo_imovel'], name='idx_tipo_imovel'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='preferenciaalerta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_alertas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='notificacaoenviada',
            name='preferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='auctions.preferenciaalerta', verbose_name='Preferência'),
        ),
        migrations.AddConstraint(
            model_name='notificacaoenviada',
            constraint=models.UniqueConstraint(fields=('preferencia', 'numero_imovel', 'uf', 'tipo_evento', 'dt'), name='uniq_notificacao_envio'),
        ),
    ]
